networks:
  gitea:
    name: gitea
    external: false

volumes:
  data:
    driver: local
  postgres:
    driver: local
  # mysql:
  #   driver: local

services:
  server:
    image: docker.io/gitea/gitea:1.23.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=db:${DB_PORT}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWORD}
    networks:
      - gitea
    restart: always
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  db:
    image: docker.io/library/postgres:14
    container_name: ${DB_TYPE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - gitea
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # db:
  #   image: docker.io/library/mysql:8
  #   container_name: ${DB_TYPE}
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   networks:
  #     - gitea
  #   restart: always
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   healthcheck:
  #     test: [ "CMD-SHELL", "mysqladmin ping -u ${DB_USER} -p${DB_PASSWORD}" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s
